feat: cyclonedx parser
open-policy-agent/conftest pull request #637
Opened 2021-11-15 11:29 UTC by developer-guy

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>

cc: @jalseth @dentrax

2021-11-24 19:37 UTC, developer-guy commented
kindly ping @jalseth

2021-11-25 20:00 UTC, jpreese commented
@developer-guy thanks for the PR. This seems straight-forward to me. Couple of thoughts:

- Would it be possible to use a smaller test fixture for this functionality? 11,000+ lines is quite.. bulky, and I think a much much smaller example, even if a little fabricated, may be a bit more digestable.
- Could some tests be added for this?

Thanks!

2021-11-25 23:37 UTC, boranx commented
+1 to adding unit tests, also we might consider having an example with an appropriate policy under [examples/](https://github.com/open-policy-agent/conftest/tree/master/examples) that could be shown in the documentation.

2021-11-26 08:00 UTC, developer-guy commented
thank you so much, folks @boranx @jpreese. I've updated the according to your requests.

![Screen Shot 2021-11-26 at 10 53 22](https://user-images.githubusercontent.com/16693043/143546659-3e502430-e2ef-44cb-8693-d32ea077a866.png)

2021-11-26 11:13 UTC, boranx requested changes
nice! I've left 2 more minor thing 
other than those, would you like to include your test to [acceptance.bats](https://github.com/open-policy-agent/conftest/blob/master/acceptance.bats) to make sure the functionality is ok always

Thanks for picking up this&for the contributions :+1:

2021-11-28 21:17 UTC, jalseth commented
@developer-guy As an aside, please copy/paste errors, terminal text, etc. into the comments rather than using screenshots as we want to be inclusive of everyone including those that need to rely on screen readers.

2021-11-29 11:48 UTC, developer-guy commented on report.json
> +<?xml version="1.0" encoding="UTF-8"?>
I added them unintentionally. I created those just for local testing. I removed them right now. Thank you.

2021-11-29 11:48 UTC, developer-guy commented on bom.json
> +{
same, I removed this one too.

2021-11-29 13:20 UTC, Dentrax commented
Hey @boranx! Just updated to c3003d02e5edcc2ddfc7bfdb68947abd6cc4f5f3, this commit adds new `XML` support for `cyclonedx`, which is [built-in supported](https://github.com/CycloneDX/cyclonedx-go/blob/e0d515e31f467886d1d5370247d34160ab56b3e9/cyclonedx.go#L70-L75).

2021-11-30 11:06 UTC, boranx approved these changes
/lgtm thanks!

2021-11-30 11:13 UTC, merged