fix: Add tls flag to test command
open-policy-agent/conftest pull request #908
Opened 2024-01-19 02:33 UTC by oblogic7

The pull command uses TLS by default by way of the value set for the `tls` flag.  This change updates the `--update` flag on the test command to use TLS by default to align with the pull command.

2024-01-19 15:28 UTC, IcaroBichir approved these changes

2024-01-20 17:44 UTC, jalseth requested changes
Thanks for the PR.

2024-01-20 17:44 UTC, jalseth commented on internal/commands/test.go
> +			if err := viper.BindPFlag("tls", cmd.Flags().Lookup("tls")); err != nil {
Instead of this, please add `tls` to the list above.

2024-01-20 17:44 UTC, jalseth commented on internal/commands/test.go
> +	cmd.Flags().BoolP("tls", "s", true, "Use TLS to access the registry")
Please make this a `Bool()` call rather than `BoolP`. A single-letter alias of `s` for the `tls` flag does not make sense.

2024-01-28 16:54 UTC, jalseth commented
@oblogic7 If you would like this change to be in the next conftest release, please update the CL in the next couple of days.

2024-01-30 14:32 UTC, oblogic7 commented
Sorry for the delay.  This should be ready now.

2024-02-01 03:32 UTC, jalseth approved these changes

2024-02-01 03:33 UTC, merged

2024-02-01 03:33 UTC, jalseth commented
No problem, I just wanted to make sure this would make it in the release. Thanks for the PR!