feat: Use ORAS credentials
open-policy-agent/conftest pull request #917
Opened 2024-02-13 10:53 UTC by zregvart

The OCI go-getter support implemented in Conftest uses github.com/cpuguy83/dockercfg. With ORAS v2.4.0 the credentials support[1] was integrated in the oras-go. This makes for a good opportunity to switch to using that instead. In addition to using the supported credentials implementation this allows the use of Docker native credential helpers[2].

This implementation is also a bit more correct, as it avoids using the global default HTTP client, so mutations of it, e.g. when setting the user-agent, do not cause race issues.

[1] https://github.com/oras-project/oras-credentials-go
[2] https://docs.docker.com/engine/reference/commandline/login/#credential-helpers

2024-02-15 04:33 UTC, jalseth requested changes
Thanks for the PR, this makes sense to me. One minor nit.

2024-02-15 04:33 UTC, jalseth commented on internal/registry/client_test.go
> +				t.Error(err)
I think this should be t.Fatal instead. If this fails, there's no need to continue in the test.

2024-02-15 13:36 UTC, jpreese approved these changes

2024-02-16 02:32 UTC, jalseth approved these changes
Thanks again!

2024-02-16 02:33 UTC, merged